### ISSUE TITLE
UI Group

### ISSUE THREAD

**Issue by Yiiiiiiifeiiiiiiii** [sunzhaoyuan/Live#4]
UI 

- [ ] [Milestone 1 Checklist](https://github.com/sunzhaoyuan/Live/issues/4#issuecomment-379368059)

**Comment by sunzhaoyuan** [comment]
## Milestone 1 - Due April 20th
- [ ] First Screen (Yifei Chen)
    * Reference: [DJMax Respect 2:23 - 2:47](https://youtu.be/6tEI1P-5xN8?t=2m33s)
- [x] Title Screen (Qiuyun Li)
    - [x] "New Game & Continue" feature
    - [x] "Credit" screen
- [ ] Settings Screen with clickable tabs (Zezhi Xia)

_Reference: [Game Logo](https://drive.google.com/file/d/1wUJcxVehAZppE0te5DKxN_zusKYfq477/view?usp=sharing)_
