### ISSUE TITLE
Logistics and Supports

### ISSUE THREAD

**Issue by sunzhaoyuan** [sunzhaoyuan/Live#5]
# Table of Contents
* Tutorials
    * [Survival Shooter Tutorial](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-377847313)
    * [Animation for Humanoid Characters](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-377850152)
* Supports
    - [x] [SceneLoader](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-378475248)
    - [x] [EZ CameraShake](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-378511648)
    - [x] [Multiple Game Related Assets](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-378810621)
    - [x] [AudioManager](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-379060626)
    - [x] [FollowCamera](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-379136609)
    - [ ] [Perlin Auto-Generated Terrain](https://github.com/sunzhaoyuan/Live/issues/5#issuecomment-379141301)
    - [ ] Unity LOD (Level of Details)

_Checked means "it's in the master branch"_

**Comment by sunzhaoyuan** [comment]
## Survival Shooter Tutorial
A great official Top-down shooter game tutorial by Unity official
[Survival Shooter Tutorial](https://unity3d.com/learn/tutorials/s/survival-shooter-tutorial)

**Comment by sunzhaoyuan** [comment]
I've created a **new branch called _iss5-supports_**. It is a place that has some supportive classes which can be used on other GOs.

**Comment by sunzhaoyuan** [comment]
## **Animation for Humanoid characters**
In this case - Ethan is our character
[Humanoid Avatars Tutorial](https://unity3d.com/learn/tutorials/topics/animation/humanoid-avatars?playlist=17099)

**Comment by sunzhaoyuan** [comment]
## New Support - SceneLoader (.../__Scene/Supports/)
The SceneLoader is a GameObject that can load a scene given a scene name. 
You can use the SceneLoader in a **button's OnClick() event** or just simply **call the non-static method LoadLevel()**. 

Additional features:
- [x] Progress Bar
- [ ] Showing Logo OnTop
- [x] Smooth Transition (fading from black)

**Comment by sunzhaoyuan** [comment]
## New Support - EZ CameraShake (.../_Assets/Supports/)
EZ Camera Shake provides multiple options for camera shaking. It can be **edited in the inspector** when attached to a camera object or be **modified in the script by calling EZCameraShake.Instance** Details see its documentation or sample scripts.

**Comment by sunzhaoyuan** [comment]
## New Support - Multiple Assets (.../_Assets/Supports/Unimported)
These assets are free licensed meaning that they can be used in both non-commercial and commercial projects. **They have not been imported into the project yet**

### Assets Showroom:
1. Arena <img src="http://devassets.com/img/assets/medieval-arena/Banner.jpg"/>
1. General Texture Pack <img src="http://devassets.com/img/assets/general-textures/Banner.jpg"/>
1. Modern Weapons <img src="http://devassets.com/img/assets/modern-weapons/Banner.jpg"/>
1. Sci-Fi Weapons <img src="http://devassets.com/img/assets/sci-fi-weapons/Banner.jpg"/>
1. Survival Weapons <img src="http://devassets.com/img/assets/survival-weapons/Banner.jpg"/>
1. Military Vehicles <img src="http://devassets.com/img/assets/military-vehicles/Banner.jpg"/>
1. Sci-Fi Vehicles <img src="http://devassets.com/img/assets/sci-fi-vehicles/Banner.jpg"/>
1. Adventure Starter Pack <img src="http://devassets.com/img/assets/adventure-starter-pack/Banner.jpg"/>

Credit: [Dev Assets](http://devassets.com/browse/)

**Comment by sunzhaoyuan** [comment]
## New Support - AudioManager (.../_Prefabs/Supports/)
AudioManager can manager multiple AudioSource and Play them. One nice feature of it is that it will not restart the current music when we switch the scene. Details see the AudioManager_Demo scene (.../__Scene/Supports/)

In the demo scene you can click two buttons to listen clips of my favorite songs. 

**Features List:**
- [x] Play Audio in Loop
- [x] Keep Playing between Scenes
- [ ] Methods extendable

**Comment by sunzhaoyuan** [comment]
## New Support - TopDown FollowCamera (.../__Scene/Supports/)
TopDown Camera demo is in the directory above. The MainCamera will always follow the player (cube) in a smooth way. The FollowCamera script is under (.../_Scripts/Supports/FollowCamera). The player(cube) has a SimpleMove script to control its movement. 

**TODOs:**
- [ ] Fix the little tilt of the camera angle when at edge
- [ ] Orthographic? Perspective?

**Comment by sunzhaoyuan** [comment]
## New Support - Perlin Auto-Generate Terrain (.../__Scene/Supports/)
By applying Perlin calculation, we can generate a random terrain with 3D textures in run-time. Check the demo scene and try to change values of Scale, OffsetX, OffsetY, and Depth. 

<img src="https://i.ytimg.com/vi/Rl8Kj8M0Bjo/hqdefault.jpg"/>


</br>

## New Support - Advanced Perlin Map Generator (.../__Scene/Supports/AdvancedPerlinTerrain_Demo)
**In Developing**
Support adjusting multiple variables such as Octaves, Persistance, Lacunarity, and seed.
<img src="http://i.stack.imgur.com/sO0t5.png"/>

**Comment by sunzhaoyuan** [comment]
## Support In Construction - Unity LOD

**Comment by sunzhaoyuan** [comment]
project finished.
